// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt-aEeHAY6CdPSDP5idzkz-TMsoFq9b8U',
    appId: '1:226558553838:web:bd1f5a8bbe3cc960b88dff',
    messagingSenderId: '226558553838',
    projectId: 'smartfin-afa77',
    authDomain: 'smartfin-afa77.firebaseapp.com',
    storageBucket: 'smartfin-afa77.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-TOi8vmUnKISIfnwC4vKfd36AX7YTy4k',
    appId: '1:226558553838:android:025a3ed165267616b88dff',
    messagingSenderId: '226558553838',
    projectId: 'smartfin-afa77',
    storageBucket: 'smartfin-afa77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP7LVwKI_cbsfHeEn3L-g-SeUL1AUrC4c',
    appId: '1:226558553838:ios:37f6a997252004dcb88dff',
    messagingSenderId: '226558553838',
    projectId: 'smartfin-afa77',
    storageBucket: 'smartfin-afa77.appspot.com',
    iosClientId: '226558553838-75luruvtt5qi4kou656dc43mv03u36tu.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartFinFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP7LVwKI_cbsfHeEn3L-g-SeUL1AUrC4c',
    appId: '1:226558553838:ios:e6a192a9ab8c1fe7b88dff',
    messagingSenderId: '226558553838',
    projectId: 'smartfin-afa77',
    storageBucket: 'smartfin-afa77.appspot.com',
    iosClientId: '226558553838-45k6ehi0ri4rs0ao1u3uqcsa7oekpipi.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartFinFlutter.RunnerTests',
  );
}
